### ISSUE TITLE
Thanks for this repo!

### ISSUE THREAD

**Issue by pReya** [eridur-de/epilog-fusion-pro-32#40]
Feel free to close this issue, as it's off topic. Just wanted to say thank you for this repo! It's so nice that someone takes the time to write down all these bugs. These machines are so expensive and scarce that it's hard to connect with other customers, and our problems are easily dismissable. Seeing what problems other customers have helps a lot!

We're running a Fusion Maker 24 at our [workshop](https://www.welcome-werkstatt.de/). I'll try to recreate some/most of your bugs and see if they exist for our model, too.

Thanks for the great open source spirit.

**Comment by vmario89** [comment]
some of my issues are not well described and are really specific. i just started with this because epilog doesn't like to answer or fix issues or to create change log which present the real things they changed in software. thats a pitty for almost 5 years now ...

**Comment by pReya** [comment]
Yeah, I know, it's a shame how they handle their software development. They only get away with it, because customers are so rare and not very well connected. So they can always act surprised, like they've never heard about something before.

Thanks for doing this! I hope I can help with some improvements.

**Comment by vmario89** [comment]
let me know if you need some more infos about the one or other thing about Epilog lasers. We can keep connection up :)
